### ISSUE TITLE
Is use of Relu nonlinearity supported by the method?

### ISSUE THREAD

**Issue by 5183nischal** [garrettkatz/directional-fibers#1]
When I try the example from readme with Relu, (the jacobian is 0 always), then I get various errors. Want to make sure this that the method supports it. Thanks!

**Comment by garrettkatz** [comment]
The method does not support Relu directly, but you can use it with softplus, the smooth relaxation of Relu.  I just pushed an example of this in the file `dfibers/examples/rnn_softplus.py`, which you can run from the repository top-level directory with

```bash
python -m dfibers.examples.rnn_softplus
```

It will plot and save a figure like this:

![rnn_softplus](https://github.com/user-attachments/assets/797bb2ce-7c0f-417a-80b0-14f0bd847085)

The dynamical system in this example has the form v(t+1) = softplus(Wv(t) + b).

The reason you can not use Relu directly is that the method requires the dynamical system to be smooth and its Jacobian to be full rank at every fixed point.  Relu is not smooth at the origin and the resulting Jacobian is low rank outside the positive orthant where the derivative of Relu is zero.

Since softplus is a relaxation, it will return approximate solutions: fixed points that are close to, but not exactly equal to, the fixed points of the Relu system.  Once you have those approximations you might be able to make them more accurate by applying some local search strategy.

Whether you get any interesting fixed points depends on the network parameters and which fiber you traverse. The latter depends in turn on which initial point you select for traversal.  I tried random parameters and initial points until I found the picture above; other configurations sometimes found fewer or no fixed points.

To see how I arrived at the network parameters in the source code, it may also help to briefly consider the 1D case where f(v) = Relu(wv + b).  Setting x = wv + b, we get v = x/w - b/w, and fixed points occur when Relu(x) = v.  Geometrically, this means we are looking for the intersections of Relu(x) with the line y = x/w - b/w, whose slope is 1/w and whose intercept is -b/w.  The intersections are the fixed points.

If the intercept is negative and the slope is between 0 and 1, there is no intersection.  If the intercept is zero, most slopes (except 0 or 1) will only intersect Relu at the origin.  If w > 1 and b < -w, there will be two intersections, and in higher dimension N with a diagonal W and two possible intersections in every coordinate, I believe there will be 2**N fixed points.  For example, in the plot above where N = 2, there are 4 fixed points.

Hope that helps!
